
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package com.igt.interactivegame.poc.mock.ns.impl;

import com.wagerworks.rgsxt.soap.v1.AuthCustomerResponse;
import com.wagerworks.rgsxt.soap.v1.AuthHeaderResponse;
import com.wagerworks.rgsxt.soap.v1.GameDetailsResponse;
import com.wagerworks.rgsxt.soap.v13.RgsXTv13GetPlayerBalance;
import com.wagerworks.rgsxt.soap.v13.XTException;
import com.wagerworks.rgsxt.soap.v3.GetPlayerBalance;
import com.wagerworks.rgsxt.soap.v6.GetPlayerBalanceBodyResponse;
import com.wagerworks.rgsxt.soap.v6.GetPlayerBalanceResponse;
import com.wagerworks.rgsxt.soap.v6.GetPlayerBalanceResponseStatusEnum;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-05T13:15:44.884+08:00
 * Generated source version: 3.2.6
 */
@WebService(
        serviceName = "RgsXTServiceV13GetPlayerBalance",
        portName = "RgsXTv13GetPlayerBalance",
        targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
        wsdlLocation = "classpath:wsdl/rgsXTv13-getPlayerBalance.wsdl",
        endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13GetPlayerBalance")
public class RgsXTv13GetPlayerBalanceImpl implements RgsXTv13GetPlayerBalance {
    private static final Logger LOG = Logger.getLogger(RgsXTv13GetPlayerBalanceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13GetPlayerBalance#getPlayerBalance(com.wagerworks.rgsxt.soap.v3.GetPlayerBalance getPlayerBalanceRequest)*
     */
    public GetPlayerBalanceResponse getPlayerBalance(GetPlayerBalance getPlayerBalanceRequest) throws
            XTException {
        LOG.info("Executing operation getPlayerBalance");
        System.out.println(getPlayerBalanceRequest);
        try {
            GetPlayerBalanceResponse _return = new GetPlayerBalanceResponse();
            AuthHeaderResponse headerResponse = new AuthHeaderResponse();
            AuthCustomerResponse authCustomerResponse = new AuthCustomerResponse();
            authCustomerResponse.setSecureToken(getPlayerBalanceRequest.getHeader().getCustomer().getSecureToken());
            authCustomerResponse.setCcyCode(getPlayerBalanceRequest.getHeader().getCustomer().getCcyCode());
            authCustomerResponse.setUserId(getPlayerBalanceRequest.getHeader().getCustomer().getUserId());
            headerResponse.setCustomer(authCustomerResponse);
            GameDetailsResponse gameDetailsResponse = new GameDetailsResponse();
            gameDetailsResponse.setGameId(getPlayerBalanceRequest.getHeader().getGameDetails().getGameId());
            gameDetailsResponse.setName(getPlayerBalanceRequest.getHeader().getGameDetails().getName());
            headerResponse.setGameDetails(gameDetailsResponse);
            _return.setHeader(headerResponse);
            GetPlayerBalanceBodyResponse getPlayerBalanceBodyResponse = new GetPlayerBalanceBodyResponse();
            getPlayerBalanceBodyResponse.setStatus(GetPlayerBalanceResponseStatusEnum.success);
            _return.setBody(getPlayerBalanceBodyResponse);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }
}
