
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package com.igt.interactivegame.poc.mock.ns.impl;

import com.wagerworks.rgsxt.soap.v1.CustomerResponse;
import com.wagerworks.rgsxt.soap.v1.HeaderResponse;
import com.wagerworks.rgsxt.soap.v1.Void;
import com.wagerworks.rgsxt.soap.v12.CAPStatusEnum;
import com.wagerworks.rgsxt.soap.v12.RGSGameResponse;
import com.wagerworks.rgsxt.soap.v13.RgsXTv13Void;
import com.wagerworks.rgsxt.soap.v13.XTException;
import com.wagerworks.rgsxt.soap.v6.VoidBodyResponse;
import com.wagerworks.rgsxt.soap.v6.VoidResponse;
import com.wagerworks.rgsxt.soap.v6.VoidResponseStatusEnum;

import javax.jws.WebService;
import java.util.Date;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-05T13:09:34.329+08:00
 * Generated source version: 3.2.6
 */
@WebService(
        serviceName = "RgsXTServiceV13Void",
        portName = "RgsXTv13Void",
        targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
        wsdlLocation = "classpath:wsdl/rgsXTv13-void.wsdl",
        endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13Void")
public class RgsXTv13VoidImpl implements RgsXTv13Void {
    private static final Logger LOG = Logger.getLogger(RgsXTv13VoidImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13Void#Cancel(com.wagerworks.rgsxt.soap.v1.Void voidRequest)*
     */
    public VoidResponse Cancel(Void voidRequest) throws
            XTException {
        LOG.info("Executing operation Cancel");
        System.out.println(voidRequest);
        try {
            VoidResponse _return = new VoidResponse();
            HeaderResponse headerResponse = new HeaderResponse();
            CustomerResponse customerResponse = new CustomerResponse();
            customerResponse.setCcyCode(voidRequest.getHeader().getCustomer().getCcyCode());
            customerResponse.setUserId(voidRequest.getHeader().getCustomer().getUserId());
            headerResponse.setCustomer(customerResponse);
            _return.setHeader(headerResponse);
            VoidBodyResponse bodyResponse = new VoidBodyResponse();
            bodyResponse.setId(voidRequest.getBody().getRGSGame().getTxnId().toString());
            bodyResponse.setStatus(VoidResponseStatusEnum.settled);
            RGSGameResponse rgsGameResponse = new RGSGameResponse();
            rgsGameResponse.setCapStatus(CAPStatusEnum.NON_PENDING);
            rgsGameResponse.setTxnStartTime(new Date().getTime());
            rgsGameResponse.setFinished(true);
            rgsGameResponse.setTxnId(voidRequest.getBody().getRGSGame().getTxnId());
            bodyResponse.setRGSGame(rgsGameResponse);
            _return.setBody(bodyResponse);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }
}
