
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package com.igt.interactivegame.poc.mock.ns.impl;

import com.wagerworks.rgsxt.soap.v1.HeartBeatResponse;
import com.wagerworks.rgsxt.soap.v13.RgsXTv13HeartBeat;
import com.wagerworks.rgsxt.soap.v13.XTException;

import javax.jws.WebService;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-05T13:15:30.499+08:00
 * Generated source version: 3.2.6
 */
@WebService(
        serviceName = "RgsXTServiceV13HeartBeat",
        portName = "RgsXTv13HeartBeat",
        targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
        wsdlLocation = "classpath:wsdl/rgsXTv13-heartBeat.wsdl",
        endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13HeartBeat")
public class RgsXTv13HeartBeatImpl implements RgsXTv13HeartBeat {
    private static final Logger LOG = Logger.getLogger(RgsXTv13HeartBeatImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13HeartBeat#heartBeat(com.wagerworks.rgsxt.soap.v1.HeartBeat heartBeatRequest)*
     */
    public HeartBeatResponse heartBeat(com.wagerworks.rgsxt.soap.v1.HeartBeat heartBeatRequest) throws
            XTException {
        LOG.info("Executing operation heartBeat");
        System.out.println(heartBeatRequest);
        try {
            HeartBeatResponse _return = new HeartBeatResponse();
            Calendar cal = Calendar.getInstance();
            cal.setTime(new Date());
            DatatypeFactory dtf = null;
            try {
                dtf = DatatypeFactory.newInstance();
            } catch (DatatypeConfigurationException e) {
                e.printStackTrace();
            }
            XMLGregorianCalendar dateType = dtf.newXMLGregorianCalendar();
            dateType.setYear(cal.get(Calendar.YEAR));
            dateType.setMonth(cal.get(Calendar.MONTH) + 1);
            dateType.setDay(cal.get(Calendar.DAY_OF_MONTH));
            dateType.setHour(cal.get(Calendar.HOUR_OF_DAY));
            dateType.setMinute(cal.get(Calendar.MINUTE));
            dateType.setSecond(cal.get(Calendar.SECOND));
            _return.setTimestamp(dateType);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }
}
