
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package com.igt.interactivegame.poc.mock.ns.impl;

import com.wagerworks.rgsxt.soap.v1.AuthCustomerResponse;
import com.wagerworks.rgsxt.soap.v1.AuthHeaderResponse;
import com.wagerworks.rgsxt.soap.v1.GameDetailsResponse;
import com.wagerworks.rgsxt.soap.v1.Init;
import com.wagerworks.rgsxt.soap.v13.RgsXTv13Init;
import com.wagerworks.rgsxt.soap.v13.XTException;
import com.wagerworks.rgsxt.soap.v6.InitBodyResponse;
import com.wagerworks.rgsxt.soap.v6.InitResponse;
import com.wagerworks.rgsxt.soap.v6.InitResponseStatusEnum;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-05T13:12:46.322+08:00
 * Generated source version: 3.2.6
 */
@WebService(
        serviceName = "RgsXTServiceV13Init",
        portName = "RgsXTv13Init",
        targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
        wsdlLocation = "classpath:wsdl/rgsXTv13-init.wsdl",
        endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13Init")
public class RgsXTv13InitImpl implements RgsXTv13Init {
    private static final Logger LOG = Logger.getLogger(RgsXTv13InitImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13Init#init(com.wagerworks.rgsxt.soap.v1.Init initRequest)*
     */
    public InitResponse init(Init initRequest) throws
            XTException {
        LOG.info("Executing operation init");
        System.out.println(initRequest);
        try {
            InitResponse _return = new InitResponse();
            AuthHeaderResponse headerResponse = new AuthHeaderResponse();
            AuthCustomerResponse authCustomerResponse = new AuthCustomerResponse();
            authCustomerResponse.setSecureToken(initRequest.getHeader().getCustomer().getSecureToken());
            authCustomerResponse.setCcyCode(initRequest.getHeader().getCustomer().getCcyCode());
            authCustomerResponse.setUserId(initRequest.getHeader().getCustomer().getUserId());
            headerResponse.setCustomer(authCustomerResponse);
            GameDetailsResponse gameDetailsResponse = new GameDetailsResponse();
            gameDetailsResponse.setGameId(initRequest.getHeader().getGameDetails().getGameId());
            gameDetailsResponse.setName(initRequest.getHeader().getGameDetails().getName());
            headerResponse.setGameDetails(gameDetailsResponse);
            _return.setHeader(headerResponse);
            InitBodyResponse initBodyResponse = new InitBodyResponse();
            initBodyResponse.setStatus(InitResponseStatusEnum.success);
            _return.setBody(initBodyResponse);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }
}
