
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package com.igt.interactivegame.poc.mock.ns.impl;

import com.wagerworks.rgsxt.soap.v1.AuthCustomerResponse;
import com.wagerworks.rgsxt.soap.v1.GameDetailsResponse;
import com.wagerworks.rgsxt.soap.v12.NotifyGameInProgressRequest;
import com.wagerworks.rgsxt.soap.v12.NotifyGameInProgressResponse;
import com.wagerworks.rgsxt.soap.v12.NotifyGameInProgressResponseBody;
import com.wagerworks.rgsxt.soap.v12.NotifyGameInProgressResponseStatusEnum;
import com.wagerworks.rgsxt.soap.v13.RgsXTv13NotifyGameInProgress;
import com.wagerworks.rgsxt.soap.v13.XTException;
import com.wagerworks.rgsxt.soap.v4.AuthHeaderResponse;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-05T13:15:08.222+08:00
 * Generated source version: 3.2.6
 */
@WebService(
        serviceName = "RgsXTServiceV13NotifyGameInProgress",
        portName = "RgsXTv13NotifyGameInProgress",
        targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
        wsdlLocation = "classpath:wsdl/rgsXTv13-notifyGameInProgress.wsdl",
        endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13NotifyGameInProgress")
public class RgsXTv13NotifyGameInProgressImpl implements RgsXTv13NotifyGameInProgress {
    private static final Logger LOG = Logger.getLogger(RgsXTv13NotifyGameInProgressImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13NotifyGameInProgress#notifyGameInProgress(com.wagerworks.rgsxt.soap.v12.NotifyGameInProgressRequest notifyGameInProgressRequest)*
     */
    public NotifyGameInProgressResponse notifyGameInProgress(NotifyGameInProgressRequest notifyGameInProgressRequest)
            throws
            XTException {
        LOG.info("Executing operation notifyGameInProgress");
        System.out.println(notifyGameInProgressRequest);
        try {
            NotifyGameInProgressResponse _return = new NotifyGameInProgressResponse();
            AuthHeaderResponse headerResponse = new AuthHeaderResponse();
            AuthCustomerResponse authCustomerResponse = new AuthCustomerResponse();
            authCustomerResponse.setSecureToken(notifyGameInProgressRequest.getHeader().getCustomer().getSecureToken());
            authCustomerResponse.setCcyCode(notifyGameInProgressRequest.getHeader().getCustomer().getCcyCode());
            authCustomerResponse.setUserId(notifyGameInProgressRequest.getHeader().getCustomer().getUserId());
            headerResponse.setCustomer(authCustomerResponse);
            GameDetailsResponse gameDetailsResponse = new GameDetailsResponse();
            gameDetailsResponse.setGameId(notifyGameInProgressRequest.getHeader().getGameDetails().getGameId());
            gameDetailsResponse.setName(notifyGameInProgressRequest.getHeader().getGameDetails().getName());
            headerResponse.setGameDetails(gameDetailsResponse);
            _return.setHeader(headerResponse);
            NotifyGameInProgressResponseBody bodyResponse = new NotifyGameInProgressResponseBody();
            bodyResponse.setStatus(NotifyGameInProgressResponseStatusEnum.SUCCESS);
            _return.setBody(bodyResponse);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }
}
