
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package com.igt.interactivegame.poc.mock.ns.impl;

import com.wagerworks.rgsxt.soap.v1.CustomerResponse;
import com.wagerworks.rgsxt.soap.v1.HeaderResponse;
import com.wagerworks.rgsxt.soap.v13.RgsXTv13EndGameSession;
import com.wagerworks.rgsxt.soap.v13.XTException;
import com.wagerworks.rgsxt.soap.v5.EndGameSessionReq;
import com.wagerworks.rgsxt.soap.v6.EndGameSessionBodyResponse;
import com.wagerworks.rgsxt.soap.v6.EndGameSessionResp;
import com.wagerworks.rgsxt.soap.v6.EndGameSessionResponseStatusEnum;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-05T13:15:57.979+08:00
 * Generated source version: 3.2.6
 */
@WebService(
        serviceName = "RgsXTServiceV13EndGameSession",
        portName = "RgsXTv13EndGameSession",
        targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
        wsdlLocation = "classpath:wsdl/rgsXTv13-endGameSession.wsdl",
        endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13EndGameSession")
public class RgsXTv13EndGameSessionImpl implements RgsXTv13EndGameSession {
    private static final Logger LOG = Logger.getLogger(RgsXTv13EndGameSessionImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13EndGameSession#endGameSession(com.wagerworks.rgsxt.soap.v5.EndGameSessionReq endGameSessionRequest)*
     */
    public EndGameSessionResp endGameSession(EndGameSessionReq endGameSessionRequest) throws
            XTException {
        LOG.info("Executing operation endGameSession");
        System.out.println(endGameSessionRequest);
        try {
            EndGameSessionResp _return = new EndGameSessionResp();
            HeaderResponse headerResponse = new HeaderResponse();
            CustomerResponse customerResponse = new CustomerResponse();
            customerResponse.setCcyCode(endGameSessionRequest.getHeader().getCustomer().getCcyCode());
            customerResponse.setUserId(endGameSessionRequest.getHeader().getCustomer().getUserId());
            headerResponse.setCustomer(customerResponse);
            _return.setHeader(headerResponse);
            EndGameSessionBodyResponse endGameSessionBodyResponse = new EndGameSessionBodyResponse();
            endGameSessionBodyResponse.setStatus(EndGameSessionResponseStatusEnum.success);
            _return.setBody(endGameSessionBodyResponse);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }
}
