
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package com.igt.interactivegame.poc.mock.ns.impl;

import com.wagerworks.rgsxt.soap.v1.CustomerResponse;
import com.wagerworks.rgsxt.soap.v1.HeaderResponse;
import com.wagerworks.rgsxt.soap.v12.*;
import com.wagerworks.rgsxt.soap.v13.RgsXTv13Recon;
import com.wagerworks.rgsxt.soap.v13.XTException;
import com.wagerworks.rgsxt.soap.v9.Recon;

import javax.jws.WebService;
import java.util.Date;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-05T13:14:32.045+08:00
 * Generated source version: 3.2.6
 */
@WebService(
        serviceName = "RgsXTServiceV13Recon",
        portName = "RgsXTv13Recon",
        targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
        wsdlLocation = "classpath:wsdl/rgsXTv13-recon.wsdl",
        endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13Recon")
public class RgsXTv13ReconImpl implements RgsXTv13Recon {
    private static final Logger LOG = Logger.getLogger(RgsXTv13ReconImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13Recon#recon(com.wagerworks.rgsxt.soap.v9.Recon reconRequest)*
     */
    public ReconResponse recon(Recon reconRequest) throws
            XTException {
        LOG.info("Executing operation recon");
        System.out.println(reconRequest);
        try {
            ReconResponse _return = new ReconResponse();
            HeaderResponse headerResponse = new HeaderResponse();
            CustomerResponse customerResponse = new CustomerResponse();
            customerResponse.setCcyCode(reconRequest.getHeader().getCustomer().getCcyCode());
            customerResponse.setUserId(reconRequest.getHeader().getCustomer().getUserId());
            headerResponse.setCustomer(customerResponse);
            _return.setHeader(headerResponse);
            ReconBodyResponse bodyResponse = new ReconBodyResponse();
            bodyResponse.setId(reconRequest.getBody().getRGSGame().getTxnId().toString());
            bodyResponse.setStatus(ReconResponseStatusEnum.SETTLED);
            RGSGameResponse rgsGameResponse = new RGSGameResponse();
            rgsGameResponse.setCapStatus(CAPStatusEnum.NON_PENDING);
            rgsGameResponse.setTxnStartTime(new Date().getTime());
            rgsGameResponse.setFinished(true);
            rgsGameResponse.setTxnId(reconRequest.getBody().getRGSGame().getTxnId());
            bodyResponse.setRGSGame(rgsGameResponse);
            _return.setBody(bodyResponse);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }
}
