
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package com.igt.interactivegame.poc.mock.ns.impl;

import com.wagerworks.rgsxt.soap.v1.AuthCustomerResponse;
import com.wagerworks.rgsxt.soap.v1.GameDetailsResponse;
import com.wagerworks.rgsxt.soap.v12.*;
import com.wagerworks.rgsxt.soap.v13.RgsXTv13Play;
import com.wagerworks.rgsxt.soap.v13.XTException;
import com.wagerworks.rgsxt.soap.v8.AuthHeaderResponse;

import javax.jws.WebService;
import java.util.Date;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-05T13:14:19.852+08:00
 * Generated source version: 3.2.6
 */
@WebService(
        serviceName = "RgsXTServiceV13Play",
        portName = "RgsXTv13Play",
        targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
        wsdlLocation = "classpath:wsdl/rgsXTv13-play.wsdl",
        endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13Play")
public class RgsXTv13PlayImpl implements RgsXTv13Play {
    private static final Logger LOG = Logger.getLogger(RgsXTv13PlayImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13Play#play(com.wagerworks.rgsxt.soap.v9.Play playRequest)*
     */
    public PlayResponse play(com.wagerworks.rgsxt.soap.v9.Play playRequest) throws
            XTException {
        LOG.info("Executing operation play");
        System.out.println(playRequest);
        try {
            PlayResponse _return = new PlayResponse();
            AuthHeaderResponse headerResponse = new AuthHeaderResponse();
            AuthCustomerResponse authCustomerResponse = new AuthCustomerResponse();
            authCustomerResponse.setSecureToken(playRequest.getHeader().getCustomer().getSecureToken());
            authCustomerResponse.setCcyCode(playRequest.getHeader().getCustomer().getCcyCode());
            authCustomerResponse.setUserId(playRequest.getHeader().getCustomer().getUserId());
            headerResponse.setCustomer(authCustomerResponse);
            GameDetailsResponse gameDetailsResponse = new GameDetailsResponse();
            gameDetailsResponse.setGameId(playRequest.getHeader().getGameDetails().getGameId());
            gameDetailsResponse.setName(playRequest.getHeader().getGameDetails().getName());
            headerResponse.setGameDetails(gameDetailsResponse);
            _return.setHeader(headerResponse);
            PlayBodyResponse playBodyResponse = new PlayBodyResponse();
            playBodyResponse.setId(playRequest.getBody().getRGSGame().getTxnId().toString());
            playBodyResponse.setStatus(PlayResponseStatusEnum.SETTLED);
            RGSGameResponse rgsGameResponse = new RGSGameResponse();
            rgsGameResponse.setCapStatus(CAPStatusEnum.NON_PENDING);
            rgsGameResponse.setTxnStartTime(new Date().getTime());
            rgsGameResponse.setFinished(true);
            rgsGameResponse.setTxnId(playRequest.getBody().getRGSGame().getTxnId());
            playBodyResponse.setRGSGame(rgsGameResponse);
            _return.setBody(playBodyResponse);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }
}
