
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wagerworks.rgsxt.soap.v13;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:33.244+08:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "RgsXTServiceV13Notify",
                      portName = "RgsXTv13Notify",
                      targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
                      wsdlLocation = "classpath:wsdl/rgsXTv13-notify.wsdl",
                      endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13Notify")

public class RgsXTv13NotifyImpl implements RgsXTv13Notify {

    private static final Logger LOG = Logger.getLogger(RgsXTv13NotifyImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13Notify#notify(com.wagerworks.rgsxt.soap.v8.Notify notifyRequest)*
     */
    public com.wagerworks.rgsxt.soap.v8.NotifyResponse notify(com.wagerworks.rgsxt.soap.v8.Notify notifyRequest) throws XTException   {
        LOG.info("Executing operation notify");
        System.out.println(notifyRequest);
        try {
            com.wagerworks.rgsxt.soap.v8.NotifyResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }

}
