
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wagerworks.rgsxt.soap.v13;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:23.665+08:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "RgsXTServiceV13Init",
                      portName = "RgsXTv13Init",
                      targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
                      wsdlLocation = "classpath:wsdl/rgsXTv13-init.wsdl",
                      endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13Init")

public class RgsXTv13InitImpl implements RgsXTv13Init {

    private static final Logger LOG = Logger.getLogger(RgsXTv13InitImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13Init#init(com.wagerworks.rgsxt.soap.v1.Init initRequest)*
     */
    public com.wagerworks.rgsxt.soap.v6.InitResponse init(com.wagerworks.rgsxt.soap.v1.Init initRequest) throws XTException   {
        LOG.info("Executing operation init");
        System.out.println(initRequest);
        try {
            com.wagerworks.rgsxt.soap.v6.InitResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }

}
