package com.wagerworks.rgsxt.soap.v13;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:26.902+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/", name = "RgsXTv13Play")
@XmlSeeAlso({com.wagerworks.rgsxt.soap.v1.ObjectFactory.class, com.wagerworks.rgsxt.soap.v2.ObjectFactory.class, com.wagerworks.rgsxt.soap.v3.ObjectFactory.class, com.wagerworks.rgsxt.soap.v4.ObjectFactory.class, com.wagerworks.rgsxt.soap.v5.ObjectFactory.class, com.wagerworks.rgsxt.soap.v6.ObjectFactory.class, com.wagerworks.rgsxt.soap.v8.ObjectFactory.class, com.wagerworks.rgsxt.soap.v9.ObjectFactory.class, ObjectFactory.class, com.wagerworks.rgsxt.soap.v12.ObjectFactory.class, com.wagerworks.rgsxt.soap.v11.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RgsXTv13Play {

    @WebMethod(operationName = "Play", action = "http://www.wagerworks.com/rgsXT/soap/v8/Play")
    @WebResult(name = "PlayResponse", targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v12/", partName = "PlayResponse")
    public com.wagerworks.rgsxt.soap.v12.PlayResponse play(
        @WebParam(partName = "PlayRequest", name = "Play", targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v9/")
        com.wagerworks.rgsxt.soap.v9.Play playRequest
    ) throws XTException;
}
