package com.wagerworks.rgsxt.soap.v13;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:39.563+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "RgsXTServiceV13EndGameSession",
                  wsdlLocation = "classpath:wsdl/rgsXTv13-endGameSession.wsdl",
                  targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/")
public class RgsXTServiceV13EndGameSession extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.wagerworks.com/rgsXT/soap/v13/", "RgsXTServiceV13EndGameSession");
    public final static QName RgsXTv13EndGameSession = new QName("http://www.wagerworks.com/rgsXT/soap/v13/", "RgsXTv13EndGameSession");
    static {
        URL url = RgsXTServiceV13EndGameSession.class.getClassLoader().getResource("wsdl/rgsXTv13-endGameSession.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RgsXTServiceV13EndGameSession.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/rgsXTv13-endGameSession.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RgsXTServiceV13EndGameSession(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RgsXTServiceV13EndGameSession(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RgsXTServiceV13EndGameSession() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RgsXTServiceV13EndGameSession(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RgsXTServiceV13EndGameSession(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RgsXTServiceV13EndGameSession(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RgsXTv13EndGameSession
     */
    @WebEndpoint(name = "RgsXTv13EndGameSession")
    public RgsXTv13EndGameSession getRgsXTv13EndGameSession() {
        return super.getPort(RgsXTv13EndGameSession, RgsXTv13EndGameSession.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RgsXTv13EndGameSession
     */
    @WebEndpoint(name = "RgsXTv13EndGameSession")
    public RgsXTv13EndGameSession getRgsXTv13EndGameSession(WebServiceFeature... features) {
        return super.getPort(RgsXTv13EndGameSession, RgsXTv13EndGameSession.class, features);
    }

}
