
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wagerworks.rgsxt.soap.v13;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:39.531+08:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "RgsXTServiceV13EndGameSession",
                      portName = "RgsXTv13EndGameSession",
                      targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
                      wsdlLocation = "classpath:wsdl/rgsXTv13-endGameSession.wsdl",
                      endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13EndGameSession")

public class RgsXTv13EndGameSessionImpl implements RgsXTv13EndGameSession {

    private static final Logger LOG = Logger.getLogger(RgsXTv13EndGameSessionImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13EndGameSession#endGameSession(com.wagerworks.rgsxt.soap.v5.EndGameSessionReq endGameSessionRequest)*
     */
    public com.wagerworks.rgsxt.soap.v6.EndGameSessionResp endGameSession(com.wagerworks.rgsxt.soap.v5.EndGameSessionReq endGameSessionRequest) throws XTException   {
        LOG.info("Executing operation endGameSession");
        System.out.println(endGameSessionRequest);
        try {
            com.wagerworks.rgsxt.soap.v6.EndGameSessionResp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }

}
