
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wagerworks.rgsxt.soap.v13;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:26.878+08:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "RgsXTServiceV13Play",
                      portName = "RgsXTv13Play",
                      targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
                      wsdlLocation = "classpath:wsdl/rgsXTv13-play.wsdl",
                      endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13Play")

public class RgsXTv13PlayImpl implements RgsXTv13Play {

    private static final Logger LOG = Logger.getLogger(RgsXTv13PlayImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13Play#play(com.wagerworks.rgsxt.soap.v9.Play playRequest)*
     */
    public com.wagerworks.rgsxt.soap.v12.PlayResponse play(com.wagerworks.rgsxt.soap.v9.Play playRequest) throws XTException   {
        LOG.info("Executing operation play");
        System.out.println(playRequest);
        try {
            com.wagerworks.rgsxt.soap.v12.PlayResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }

}
