
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wagerworks.rgsxt.soap.v13;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:45.783+08:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "RgsXTServiceV13NotifyGameInProgress",
                      portName = "RgsXTv13NotifyGameInProgress",
                      targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/",
                      wsdlLocation = "classpath:wsdl/rgsXTv13-notifyGameInProgress.wsdl",
                      endpointInterface = "com.wagerworks.rgsxt.soap.v13.RgsXTv13NotifyGameInProgress")

public class RgsXTv13NotifyGameInProgressImpl implements RgsXTv13NotifyGameInProgress {

    private static final Logger LOG = Logger.getLogger(RgsXTv13NotifyGameInProgressImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wagerworks.rgsxt.soap.v13.RgsXTv13NotifyGameInProgress#notifyGameInProgress(com.wagerworks.rgsxt.soap.v12.NotifyGameInProgressRequest notifyGameInProgressRequest)*
     */
    public com.wagerworks.rgsxt.soap.v12.NotifyGameInProgressResponse notifyGameInProgress(com.wagerworks.rgsxt.soap.v12.NotifyGameInProgressRequest notifyGameInProgressRequest) throws XTException   {
        LOG.info("Executing operation notifyGameInProgress");
        System.out.println(notifyGameInProgressRequest);
        try {
            com.wagerworks.rgsxt.soap.v12.NotifyGameInProgressResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new XTException("XTException...");
    }

}
