package com.wagerworks.rgsxt.soap.v13;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:26.911+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "RgsXTServiceV13Play",
                  wsdlLocation = "classpath:wsdl/rgsXTv13-play.wsdl",
                  targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/")
public class RgsXTServiceV13Play extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.wagerworks.com/rgsXT/soap/v13/", "RgsXTServiceV13Play");
    public final static QName RgsXTv13Play = new QName("http://www.wagerworks.com/rgsXT/soap/v13/", "RgsXTv13Play");
    static {
        URL url = RgsXTServiceV13Play.class.getClassLoader().getResource("wsdl/rgsXTv13-play.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RgsXTServiceV13Play.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/rgsXTv13-play.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RgsXTServiceV13Play(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RgsXTServiceV13Play(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RgsXTServiceV13Play() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RgsXTServiceV13Play(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RgsXTServiceV13Play(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RgsXTServiceV13Play(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RgsXTv13Play
     */
    @WebEndpoint(name = "RgsXTv13Play")
    public RgsXTv13Play getRgsXTv13Play() {
        return super.getPort(RgsXTv13Play, RgsXTv13Play.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RgsXTv13Play
     */
    @WebEndpoint(name = "RgsXTv13Play")
    public RgsXTv13Play getRgsXTv13Play(WebServiceFeature... features) {
        return super.getPort(RgsXTv13Play, RgsXTv13Play.class, features);
    }

}
