package com.wagerworks.rgsxt.soap.v13;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:20.458+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "RgsXTServiceV13Void",
                  wsdlLocation = "classpath:wsdl/rgsXTv13-void.wsdl",
                  targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v13/")
public class RgsXTServiceV13Void extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.wagerworks.com/rgsXT/soap/v13/", "RgsXTServiceV13Void");
    public final static QName RgsXTv13Void = new QName("http://www.wagerworks.com/rgsXT/soap/v13/", "RgsXTv13Void");
    static {
        URL url = RgsXTServiceV13Void.class.getClassLoader().getResource("wsdl/rgsXTv13-void.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RgsXTServiceV13Void.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/rgsXTv13-void.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RgsXTServiceV13Void(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RgsXTServiceV13Void(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RgsXTServiceV13Void() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RgsXTServiceV13Void(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RgsXTServiceV13Void(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RgsXTServiceV13Void(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RgsXTv13Void
     */
    @WebEndpoint(name = "RgsXTv13Void")
    public RgsXTv13Void getRgsXTv13Void() {
        return super.getPort(RgsXTv13Void, RgsXTv13Void.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RgsXTv13Void
     */
    @WebEndpoint(name = "RgsXTv13Void")
    public RgsXTv13Void getRgsXTv13Void(WebServiceFeature... features) {
        return super.getPort(RgsXTv13Void, RgsXTv13Void.class, features);
    }

}
