
package com.wagerworks.rgsxt.soap.v13;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T09:36:45.724+08:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "XTException", targetNamespace = "http://www.wagerworks.com/rgsXT/soap/v1/")
public class XTException extends Exception {

    private com.wagerworks.rgsxt.soap.v1.XTException xtException;

    public XTException() {
        super();
    }

    public XTException(String message) {
        super(message);
    }

    public XTException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public XTException(String message, com.wagerworks.rgsxt.soap.v1.XTException xtException) {
        super(message);
        this.xtException = xtException;
    }

    public XTException(String message, com.wagerworks.rgsxt.soap.v1.XTException xtException, java.lang.Throwable cause) {
        super(message, cause);
        this.xtException = xtException;
    }

    public com.wagerworks.rgsxt.soap.v1.XTException getFaultInfo() {
        return this.xtException;
    }
}
